In [1]:
#Question 2
import numpy as np

#Creating  a 2D array
monthly_temperatures = [
    [20, 22, 25, 28, 30, 32, 34, 33, 30, 27, 24, 21],  # 1st year
    [19, 21, 24, 27, 29, 31, 33, 32, 29, 26, 23, 20],  # 2nd year
    [18, 20, 23, 26, 28, 30, 32, 31, 28, 25, 22, 19],  # 3rd year
    [21, 23, 26, 29, 31, 33, 35, 34, 31, 28, 25, 22],  # 4th year
    [22, 24, 27, 30, 32, 34, 36, 35, 32, 29, 26, 23]   # 5th year
]

#Numpy array named temperature_data
temperature_data = np.array(monthly_temperatures)

#Prints out results
print(temperature_data)

[[20 22 25 28 30 32 34 33 30 27 24 21]
 [19 21 24 27 29 31 33 32 29 26 23 20]
 [18 20 23 26 28 30 32 31 28 25 22 19]
 [21 23 26 29 31 33 35 34 31 28 25 22]
 [22 24 27 30 32 34 36 35 32 29 26 23]]


In [2]:
import pandas as pd
import plotly.express as px

# Convert this into a DataFrame
years = ['2020', '2021', '2022', '2023','2024']
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

# Create a list of dictionaries for the DataFrame
data = []
for year_idx, year in enumerate(years):
    for month_idx, month in enumerate(months):
        data.append({'Year': year, 'Month': month, 'Temperature': temperature_data[year_idx, month_idx]})

df = pd.DataFrame(data)

# Create a box plot using Plotly Express with 'Year' on the x-axis and 'Temperature' on the y-axis
#Add color to each month to make it more readable
fig = px.box(df, x='Month', y='Temperature', color='Month', title='Monthly Temperature Distribution Over the Past Five Years')

# Update axis labels
fig.update_layout(
    xaxis_title='Month',
    yaxis_title='Temperature (°C)'
)

# Show the plot
fig.show()

In [3]:
import plotly.graph_objs as go


# Define the month names and years
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
years = ['2020', '2021', '2022', '2023','2024']

# Create the heatmap and use 'Hot' for color scale
fig = go.Figure(data=go.Heatmap(
                   z=temperature_data,
                   x=months,
                   y=years,
                   colorscale='Hot'))

# Update layout
fig.update_layout(
    title='Average Monthly Temperatures Over the Past Five Years',
    xaxis_title='Month',
    yaxis_title='Year'
)

# Show plot
fig.show()